### ISSUE TITLE
ME Terminal Part doesn't render faces correctly.

### ISSUE THREAD

**Issue by Coppertine** [GregTechCEu/ShaderTech#4]
![image](https://user-images.githubusercontent.com/37494321/209897359-def42596-d948-4978-bb30-d366d2d9a0ea.png)

Mods:
(All from GCP 1.4.0, with additional mods but none of which should change graphically. Also no Optifine.)
![image](https://user-images.githubusercontent.com/37494321/209897598-aad979fe-4d28-4f36-98e3-3081b8cd0894.png)
In particular to mod versions above for PAE2

System Information:
CPU: Intel i5-9600K
GPU: Nvidia RTX 3090
GPU Driver: Game Ready 527.66

No additional logs as I can find.

**Comment by tukib** [comment]
Same issue with appliedenergistics2-rv6-stable-7-extended_life-v0.54.16 on nomifactory ceu 1.4.3. However, the custom emissives and ME panels do work correctly when using optifine.

Intel i7-8700K, Nvidia GTX 1070, Game Ready Driver 526.86

**Comment by Zalgo239** [comment]
This was an issue on AE2's side, make sure to be using the latest version of this fork:
https://www.curseforge.com/minecraft/mc-mods/ae2-extended-life
And it will be fixed
